### ISSUE TITLE
Problem deleting Objects

### ISSUE THREAD

**Issue by ElManueh** [eclipse-windowbuilder/windowbuilder#634]
If i create a Jpanel BorderLayout and i insert other Jpanel inside, i have a problem deleting it. Index 1 length 0.

```
package umu.tds.vista.main;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.BorderLayout;
import javax.swing.JLabel;

public class dsad extends JFrame {

	private static final long serialVersionUID = 1L;
	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					dsad frame = new dsad();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public dsad() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

		setContentPane(contentPane);
		contentPane.setLayout(new BorderLayout(0, 0));
		
		JLabel lblNewLabel = new JLabel("New label");
		contentPane.add(lblNewLabel, BorderLayout.CENTER);
		remove(lblNewLabel);
		
	}

}
```
I cant delete, for example here, the JLabel. Here its the problem.

```
Full context stack trace:
java.lang.IndexOutOfBoundsException: Index: 1, Length: 0
	at org.apache.commons.lang.ArrayUtils.remove(ArrayUtils.java:4867)
	at org.apache.commons.lang.ArrayUtils.remove(ArrayUtils.java:4287)
	at org.eclipse.wb.internal.core.utils.ast.binding.DesignerMethodBinding.removeParameterType(DesignerMethodBinding.java:93)
	at org.eclipse.wb.internal.core.utils.ast.AstEditor.removeInvocationArgument(AstEditor.java:3185)
	at org.eclipse.wb.internal.core.utils.ast.AstEditor.removeInvocationArgument(AstEditor.java:3147)
	at org.eclipse.wb.internal.swing.model.layout.LayoutInfo.removeComponentConstraints(LayoutInfo.java:309)
	at org.eclipse.wb.internal.swing.model.layout.LayoutInfo$1.before(LayoutInfo.java:103)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.wb.core.model.broadcast.BroadcastSupport.lambda$0(BroadcastSupport.java:207)
	at org.eclipse.wb.core.model.broadcast.ObjectInfoDelete$ByteBuddy$oIyRTsZH.before(Unknown Source)
	at org.eclipse.wb.core.model.JavaInfo$7.run(JavaInfo.java:812)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:331)
	at org.eclipse.wb.core.model.JavaInfo.delete(JavaInfo.java:805)
	at org.eclipse.wb.core.model.AbstractComponentInfo.delete(AbstractComponentInfo.java:226)
	at org.eclipse.wb.internal.core.editor.actions.DeleteAction$2.executeEdit(DeleteAction.java:123)
	at org.eclipse.wb.core.gef.command.EditCommand.lambda$0(EditCommand.java:50)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:331)
	at org.eclipse.wb.core.gef.command.EditCommand.execute(EditCommand.java:50)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.eclipse.gef.commands.CompoundCommand.execute(CompoundCommand.java:136)
	at org.eclipse.wb.core.gef.command.CompoundEditCommand.access$0(CompoundEditCommand.java:1)
	at org.eclipse.wb.core.gef.command.CompoundEditCommand.lambda$0(CompoundEditCommand.java:45)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.run(ExecutionUtils.java:331)
	at org.eclipse.wb.core.gef.command.CompoundEditCommand.execute(CompoundEditCommand.java:45)
	at org.eclipse.wb.internal.gef.core.EditDomain.executeCommand(EditDomain.java:50)
	at org.eclipse.wb.internal.core.editor.actions.DeleteAction.run(DeleteAction.java:64)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:300)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:655)
	at org.eclipse.e4.ui.bindings.keys.OutOfOrderListener.handleEvent(OutOfOrderListener.java:75)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1840)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5153)
	at org.eclipse.swt.widgets.Tree.WM_KEYDOWN(Tree.java:6274)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4776)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6142)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5040)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

Im using the latest version of Eclipse and WindowBuilder, and the project is builded with Java SE-1.8.

**Comment by ptziegler** [comment]
There is a general combination with the combination of WindowBuilder, JDT and Java 8. Note that this problem doesn't occur with newer Java versions.

Personally, I don't think there is any point investigating this project any further, given that Java 8 doesn't  even receive premium support anymore and given that several major projects moved to at least Java 11, I don't think it's worth investigating what exactly goes wrong here.

I can only encourage you to give it a shot yourself, but if you _really_ need to build the project against Java 8, then I think your best shot is to use a modern JDK (effectively Java 21) while setting the execution environment of your project to Java 8. The result is that even though you're using a newer Java version, the generated byte code is still executable with a good 'ol Java 8.

**Comment by ptziegler** [comment]
> I don't know if this is exactly what you told me.

This is exactly what I mean. If you right-click on your project and then go Properties -> Java Build Path -> Select JRE System Library -> Click Edit, you can select the execution environment for your project.

In the screenshot, I've set it to Java 8, even though I'm using Java 17. The generated byte code is still compatible with Java 8 and the compiler would even warn you, if you attempt to use any newer language features. There are a few caveats of course, but I don't think they should have a significant impact for WindowBuilder.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/c33a6f75-d234-4aad-bf40-ee4a84301a17)

**Comment by ElManueh** [comment]
Work it!! Thanks you so much.

**Comment by ElManueh** [comment]
> > I don't know if this is exactly what you told me.
> 
> This is exactly what I mean. If you right-click on your project and then go Properties -> Java Build Path -> Select JRE System Library -> Click Edit, you can select the execution environment for your project.
> 
> In the screenshot, I've set it to Java 8, even though I'm using Java 17. The generated byte code is still compatible with Java 8 and the compiler would even warn you, if you attempt to use any newer language features. There are a few caveats of course, but I don't think they should have a significant impact for WindowBuilder.
> 
> ![image](https://user-images.githubusercontent.com/70652978/283208878-c33a6f75-d234-4aad-bf40-ee4a84301a17.png)

Work it!!! Thanks you so much bro.

<3
