### ISSUE TITLE
Execution errors when opening the design tab of my MainFrame on Eclipse

### ISSUE THREAD

**Issue by Joe36y** [eclipse-windowbuilder/windowbuilder#673]
So basically im trying to create the game Trivial Pursuit on eclipse and ive finally got it working with CardLayout, however although it works when i run it i noticed that im getting execution errors for each card panel when trying to open the design tab of the my MainFrame frame.

Stack Trace:

java.lang.ClassCastException: Cannot cast javax.swing.JFrame to guiFrames.MainFrame
    at java.base/java.lang.Class.cast(Class.java:3921)
    at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
    at org.eclipse.wb.internal.swing.model.component.SwingInvocationEvaluatorInterceptor.evaluateSwing(SwingInvocationEvaluatorInterceptor.java:73)
    at org.eclipse.wb.internal.swing.model.component.SwingInvocationEvaluatorInterceptor.evaluate(SwingInvocationEvaluatorInterceptor.java:59)
    at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.tryInterceptors(InvocationEvaluator.java:398)
    at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:258)
    at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:84)
    at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:160)
    at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
    at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateExpression(JavaInfoEvaluationHelper.java:622)
    at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluate(JavaInfoEvaluationHelper.java:499)
    at org.eclipse.wb.core.model.JavaInfo$8.postVisit(JavaInfo.java:1146)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils$ExecutionFlowHandler.invoke(ExecutionFlowUtils.java:1288)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils$VisitorStub$ByteBuddy$3d2VFp9d.postVisit(Unknown Source)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3272)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3317)
    at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:303)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3317)
    at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:354)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:338)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:251)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:232)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:195)
    at org.eclipse.wb.core.model.JavaInfo.refresh_create(JavaInfo.java:1203)
    at org.eclipse.wb.core.model.ObjectInfo.refreshCreate0(ObjectInfo.java:516)
    at org.eclipse.wb.core.model.ObjectInfo.lambda$4(ObjectInfo.java:478)
    at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
    at org.eclipse.wb.core.model.ObjectInfo.lambda$3(ObjectInfo.java:478)
    at org.eclipse.wb.internal.swing.utils.SwingUtils$2.run(SwingUtils.java:78)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Full context stack trace:
java.lang.IllegalArgumentException: argument type mismatch
    at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:70)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
    at org.eclipse.wb.internal.swing.model.component.SwingInvocationEvaluatorInterceptor.evaluateSwing(SwingInvocationEvaluatorInterceptor.java:73)
    at org.eclipse.wb.internal.swing.model.component.SwingInvocationEvaluatorInterceptor.evaluate(SwingInvocationEvaluatorInterceptor.java:59)
    at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.tryInterceptors(InvocationEvaluator.java:398)
    at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:258)
    at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:84)
    at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:160)
    at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
    at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateExpression(JavaInfoEvaluationHelper.java:622)
    at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluate(JavaInfoEvaluationHelper.java:499)
    at org.eclipse.wb.core.model.JavaInfo$8.postVisit(JavaInfo.java:1146)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils$ExecutionFlowHandler.invoke(ExecutionFlowUtils.java:1288)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils$VisitorStub$ByteBuddy$3d2VFp9d.postVisit(Unknown Source)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3272)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3317)
    at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:303)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3317)
    at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3269)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:354)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:338)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:251)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:232)
    at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:195)
    at org.eclipse.wb.core.model.JavaInfo.refresh_create(JavaInfo.java:1203)
    at org.eclipse.wb.core.model.ObjectInfo.refreshCreate0(ObjectInfo.java:516)
    at org.eclipse.wb.core.model.ObjectInfo.lambda$4(ObjectInfo.java:478)
    at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
    at org.eclipse.wb.core.model.ObjectInfo.lambda$3(ObjectInfo.java:478)
    at org.eclipse.wb.internal.swing.utils.SwingUtils$2.run(SwingUtils.java:78)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassCastException: Cannot cast javax.swing.JFrame to guiFrames.MainFrame
    at java.base/java.lang.Class.cast(Class.java:3921)
    at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
    ... 49 more

And this is my MainFrame code:

```
package guiFrames;

import java.awt.CardLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.SwingConstants;

import guiPanels.AdminPanel;
import guiPanels.ASingleQuesPanel;
import guiPanels.AMultiQuesPanel;
import guiPanels.RemoveQuestionPanel;
import guiPanels.StartGame;
import guiPanels.HighScore;
import objects.GameSetup;


public class MainFrame extends JFrame {

    private static final long serialVersionUID = 1L;
    private JPanel contentPane;
    private JTextField textName;
    private String Name;
    private JPanel cardPanel;
    private CardLayout cardLayout;
    private AdminPanel adminPanel;
    private ASingleQuesPanel aSingleQuesPanel;
    private AMultiQuesPanel aMultiQuesPanel;
    private RemoveQuestionPanel removeQuestionPanel;
    private StartGame startGame;
    private HighScore highScore;
    

    /**
     * Launch the application.
     */
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    MainFrame frame = new MainFrame();
                    frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    public MainFrame() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(100, 100, 781, 497);
        contentPane = new JPanel();
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

        setContentPane(contentPane);
        contentPane.setLayout(new CardLayout());
        
        GameSetup gs = new GameSetup();

        cardLayout = (CardLayout) contentPane.getLayout();

        adminPanel = new AdminPanel(this);
        cardPanel = new JPanel();
        aSingleQuesPanel = new ASingleQuesPanel(this, gs);
        aMultiQuesPanel = new AMultiQuesPanel (this, gs);
        removeQuestionPanel = new RemoveQuestionPanel (this, gs);
        highScore = new HighScore(this);
        startGame = new StartGame(this, highScore);
        

       

        // Set the layout for cardPanel
        cardPanel.setLayout(null);

        JLabel lblNewLabel_1 = new JLabel("Name:");
        lblNewLabel_1.setBounds(199, 116, 61, 16);
        lblNewLabel_1.setVerticalAlignment(SwingConstants.BOTTOM);
        cardPanel.add(lblNewLabel_1);

        JLabel lblNewLabel = new JLabel("Trivial Pursuit");
        lblNewLabel.setFont(new Font("Lucida Grande", Font.PLAIN, 15));
        lblNewLabel.setBounds(322, 6, 118, 36);
        cardPanel.add(lblNewLabel);

        textName = new JTextField();
        textName.setBounds(272, 111, 168, 26);
        cardPanel.add(textName);
        textName.setColumns(10);

        JButton btnSubmit = new JButton("Submit");
        btnSubmit.setBounds(322, 149, 117, 29);
        cardPanel.add(btnSubmit);

        JButton btnAdmin = new JButton("Admin");
        btnAdmin.setBounds(143, 304, 117, 29);
        cardPanel.add(btnAdmin);

        JButton btnStartGame = new JButton("Play Game");
        btnStartGame.setBounds(493, 304, 117, 29);
        cardPanel.add(btnStartGame);

        contentPane.add(cardPanel, "mainPanel");
        contentPane.add(adminPanel, "adminPanel");  
        contentPane.add(aSingleQuesPanel, "aSingleQuesPanel");
        contentPane.add(aMultiQuesPanel, "aMultiQuesPanel");
        contentPane.add(removeQuestionPanel, "removeQuestionPanel");
        contentPane.add(startGame, "startGame");
        contentPane.add(highScore, "highScore");
        
        
        
        //This shows the MainFrame when the program is launched
        showMainPanel();

        btnAdmin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                showAdminPanel();
            }
        });

        btnSubmit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                Name = textName.getText();

                if (Name.isEmpty()) {
                    System.out.println("Please enter a valid name.");
                } else {
                    // Reset the text field
                    textName.setText("");
                }

            }
        });

        btnStartGame.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Check if the name is empty
                if (Name == null || Name.trim().isEmpty()) {
                    // Display an error message or take appropriate action
                    System.out.println("Please enter a valid name.");
                } else {
                    // The name is not empty, proceed to start the game
                    GameSetup gs = new GameSetup(Name);
                    showStartGamePanel();
                }
            }
        });
    }

    public void showAdminPanel() {
        cardLayout.show(contentPane, "adminPanel");
    }

    public void showMainPanel() {
        cardLayout.show(contentPane, "mainPanel");
    }
    
    public void showASingleQuesPanel() {
        cardLayout.show(contentPane, "aSingleQuesPanel");
    }
    
    public void showAMultiQuesPanel() {
        cardLayout.show(contentPane, "aMultiQuesPanel");
    }
    
    public void showRemoveQuestionPanel() {
        cardLayout.show(contentPane, "removeQuestionPanel");
    }
    
    public void showStartGamePanel() {
        cardLayout.show(contentPane, "startGame");
        highScore.reloadHighScores();
    }
    
    public void showHighScorePanel() {
        cardLayout.show(contentPane, "highScore");
    }
    
    public String playerName() {
        return Name;
    }
}
```

I think its something to do with the CardLayout since the design tab works again when i delete these:

    ```
contentPane.add(cardPanel, "mainPanel");
    contentPane.add(adminPanel, "adminPanel");  
    contentPane.add(aSingleQuesPanel, "aSingleQuesPanel");
    contentPane.add(aMultiQuesPanel, "aMultiQuesPanel");
    contentPane.add(removeQuestionPanel, "removeQuestionPanel");
    contentPane.add(startGame, "startGame");
    contentPane.add(highScore, "highScore");
```

![Screenshot_1](https://github.com/eclipse-windowbuilder/windowbuilder/assets/154611543/36f2d3ef-8e05-434c-b657-be39f704b334)

**Comment by ptziegler** [comment]
I've tried to reproduce the problem with your example but I can't seem to reproduce the problem.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/d002591d-e40a-4a9c-adc8-1fb8130eabe4)

Do you simply open the design page or are there any other steps I have to do, in order to reproduce the exception?
Granted, your example is incomplete, so I had to replace the missing classes with plain JPanels.

[MainFrame.java.txt](https://github.com/eclipse-windowbuilder/windowbuilder/files/13753510/MainFrame.java.txt)

Some general questions:

- What WindowBuilder version are you using?
- What Java version are you using?

**Comment by Joe36y** [comment]
Thank you for your reply, I'm attaching the whole project for you to have a
look at. I've tried running it on different devices but I still get the
same error.

Regarding the WindowBuilder and Java version, I'm using the 'WindowBuilder
Current' from the Eclipse Marketplace and Java version 8 Update381 (build
1.8.0_381-b09)

Appreciate the help!

**Comment by ptziegler** [comment]
> Java version 8 Update381

This is most likely the problem. I would suggest you use at least Java 17.
You can download a matching JDK from here: https://adoptium.net/

Note that Java 21 is also possible, but only with the latest WindowBuilder release.
If you still need to compile your project with Java 8, you can then simply set the execution environment to 1.8 in the project properties.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/9ad4b397-7435-4962-892c-80bbf9c49a5f)

**Comment by Joe36y** [comment]
> > Java version 8 Update381
> 
> This is most likely the problem. I would suggest you use at least Java 17. You can download a matching JDK from here: https://adoptium.net/
> 
> Note that Java 21 is also possible, but only with the latest WindowBuilder release. If you still need to compile your project with Java 8, you can then simply set the execution environment to 1.8 in the project properties.
> 
> ![image](https://private-user-images.githubusercontent.com/70652978/292516037-9ad4b397-7435-4962-892c-80bbf9c49a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTkyMTgsIm5iZiI6MTcwMzI1ODkxOCwicGF0aCI6Ii83MDY1Mjk3OC8yOTI1MTYwMzctOWFkNGIzOTctNzQzNS00OTYyLTg5MmMtODBiYmY5YzQ5YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE1MjgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZGVhM2MwNTFkZTk0Y2M0NGVjZjdhNjU3NDg5M2I3ZjgyMzQwZGU4N2FjMWU4NTVlZjUwNjMzMzg2Mjk5ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.reqdV45JZBRg0dDDjW5LhaDAKatAqop9jlOSC--XUd8)

I have just updated to Java 19 and noticed that I was on Java 17 before, but still didn't solve the problem. I managed to access the design of the mainframe by clicking on the two small arrows on the top right of the cardPanel. Its weird because the program runs perfect, only problem is the execution errors im getting. 

![Execution errors](https://github.com/eclipse-windowbuilder/windowbuilder/assets/154611543/6b54b0a0-8081-4f18-8d4a-a9db38b2a44c)

**Comment by ptziegler** [comment]
>  I managed to access the design of the mainframe by clicking on the two small arrows on the top right of the cardPanel.

The buttons just switch between the different cards. If if fails for some but not for all, then this seems to indicate that there is an issue with one of the panels.

Can you perhaps flip through all panels and check for which it works and for which it doesn't?

Can you perhaps also zip and upload the whole project? There doesn't seem to be anything wrong with the MainFrame class on its own, so I have a hard time analyzing the problem with just that...

**Comment by Joe36y** [comment]
Ive tried uploading the project but it doesn’t appear once i upload it,
could i get your email address so i send it to you?

Thanks for the patience and help

**Comment by ptziegler** [comment]
> Ive tried uploading the project but it doesn’t appear once i upload it,
could i get your email address so i send it to you?

You can't upload files to GitHub via email. For the sake of traceability, I think it's better if you instead upload it directly via the website.

Just go to this issue, drag & drop the (zipped) project into the text box and the click "Comment".

**Comment by ptziegler** [comment]
I'm closing this as "not planned", given that there hasn't been a response in over a year. If this issue still persists, feel free to reopen this item.

As some final words: The error `Exception during creation of: guiPanels.AdminPanel` is caused while trying to instantiate the MainFrame. Meaning WindowBuilder found something in your code it doesn't like. Given that I don't have access to the code, I can only speculate as to why that might be.
