### ISSUE TITLE
DesignerException: 308 when setModel() of JTable

### ISSUE THREAD

**Issue by riwarek** [eclipse-windowbuilder/windowbuilder#679]
Recently I've noticed such error when I try to set model of my table with custom one:
`private class CustomTableModel extends DefaultTableModel`

```
public MyOwnTable(Competition competition)
	{
		setCompetition(competition);
		setModel(new CustomTableModel());
		setDefaultRenderer(Object.class, new CustomTableRenderer());
		setTableProperties();
		setSorter();
	}
```

I see such error:
```
setModel(new CustomTableModel())

Exception during method invocation evaluation

An exception happened duringevaluation of

setModel(new CustomTableModel())
Method public void javax.swing.JTable.setModel(javax.swing.table.TableModel) was used with the parameters {<null>}. 
```
and stack
```
org.eclipse.wb.internal.core.utils.exception.DesignerException: 308 (Exception during method invocation evaluation). setModel(new CustomTableModel()) public void javax.swing.JTable.setModel(javax.swing.table.TableModel) {<null>}
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.invokeMethod(InvocationEvaluator.java:478)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:120)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:78)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:160)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateExpression(JavaInfoEvaluationHelper.java:622)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateMethodInvocation(JavaInfoEvaluationHelper.java:604)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluate(JavaInfoEvaluationHelper.java:537)
	at org.eclipse.wb.core.model.JavaInfo$8.postVisit(JavaInfo.java:1146)
	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils$ExecutionFlowHandler.invoke(ExecutionFlowUtils.java:1288)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils$VisitorStub$ByteBuddy$mgRolpx8.postVisit(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3257)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:354)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:338)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:251)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:232)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:195)
	at org.eclipse.wb.core.model.JavaInfo.refresh_create(JavaInfo.java:1203)
	at org.eclipse.wb.core.model.ObjectInfo.refreshCreate0(ObjectInfo.java:516)
	at org.eclipse.wb.core.model.ObjectInfo.lambda$4(ObjectInfo.java:478)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
	at org.eclipse.wb.core.model.ObjectInfo.lambda$3(ObjectInfo.java:478)
	at org.eclipse.wb.internal.swing.utils.SwingUtils$2.run(SwingUtils.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.invokeMethod(InvocationEvaluator.java:476)
	... 40 more
Caused by: java.lang.IllegalArgumentException: Cannot set a null TableModel
	at java.desktop/javax.swing.JTable.setModel(JTable.java:3740)
	... 45 more
```

I suppose evaluation  {<null>} is caused because at the moment of displaying of layout in Design it `new` may be treated as a null, but even when I make a field:
`CustomTableModel someVal = new CustomTableModel();`
and pass it, it is still evaluated as a null.

When I run app everything is displayed properly.
What I missed?

**Comment by riwarek** [comment]
Completion:
I don't know why this message happened, but after rebuild whole project I recieved new error which was connected with unitialized field. After placing it in `if` everything works like expected.
Anyway it reminds me another topic.
Is it possible to set some flag like 'lazy verification"? I mean quiet often I set a field but initialize it in constructor. It seems WindowsBuilder by default treat it like some kind of problem. Or maybe I understand this mechanism wrong?

**Comment by ptziegler** [comment]
It feels like something is missing here...

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/b6ee0e55-87e4-40df-accd-bf23101f5677)

Can you provide a minimal project that reproduces this problem?
What Java version are you using?
What WindowBuilder version are you using?

> Is it possible to set some flag like 'lazy verification"? I mean quiet often I set a field but initialize it in constructor. It seems WindowsBuilder by default treat it like some kind of problem. Or maybe I understand this mechanism wrong?

That shouldn't really be necessary. Internally, WindowBuilder creates stubs of all the classes that are used. Meaning that an error like this seems to indicate that something is going wrong somewhere.

**Comment by riwarek** [comment]
Well, now I know exactly where the problem is in my code but I don't understand why it happens. Maybe this is a feature of WB?
I am pretty sure it is connected with the class field:
`private Competition competition;'
and trial of usage of it later in the application:
```
		@Override
		public int getRowCount()
		{
			var size = 0;
			//if (competition != null)
			//{
				size = DataManager.get().loadedData.getCompetitionByHash(competition.getHash()).getParticipants().size();
			//}
			return size;
		}
```
If I will uncomment `if` everything works like a charm. If not, I see:
```
new ParticipantsTable()

Internal Error

WindowBuilder encountered unexpected internal error. 

This could be caused by a WindowBuilder bug or by a misconfiguration issue, conflict, partialupdate, etc.

java.lang.NullPointerException: Cannot invoke "packages.Competition.getHash()" because "this.this$0.competition" is null
	at packages.ParticipantsTable$CustomTableModel.getRowCount(ParticipantsTable.java:231)
```
I will try extract problematic part and provide it soon.

**Comment by ptziegler** [comment]
Is this issue still relevant?
