### ISSUE TITLE
JDialog super constructor causes exception

### ISSUE THREAD

**Issue by igarshep** [eclipse-windowbuilder/windowbuilder#743]
Hello, we meet again so soon..

Here is a sample of code that causes the problem:

    public class TestView extends JDialog {

        public TestView() {
           super(new JFrame());
           final JPanel panel = new JPanel();
           getContentPane().add(panel, BorderLayout.CENTER);
        }
    }

If I comment out 

      super(new JFrame()); 

it'll work again.

Stack trace:

org.eclipse.wb.internal.core.utils.exception.DesignerException: 313 (Exception during 'super' constructor evaluation). JDialog(Frame) {javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]} java.lang.IllegalArgumentException: java.lang.ClassCastException@67ad4e8e
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1453.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.wb.internal.core.model.creation.ThisCreationSupport.create(ThisCreationSupport.java:308)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateJavaInfoUsingCreationSupport(JavaInfoEvaluationHelper.java:634)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper$3.evaluate(JavaInfoEvaluationHelper.java:346)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:123)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:114)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:78)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:160)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateExpression(JavaInfoEvaluationHelper.java:622)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluate(JavaInfoEvaluationHelper.java:499)
	at org.eclipse.wb.core.model.JavaInfo$8.postVisit(JavaInfo.java:1146)
	at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils$ExecutionFlowHandler.invoke(ExecutionFlowUtils.java:1288)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils$VisitorStub$ByteBuddy$F6K4mfyV.postVisit(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3303)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:223)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:354)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:338)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:251)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:232)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:195)
	at org.eclipse.wb.core.model.JavaInfo.refresh_create(JavaInfo.java:1203)
	at org.eclipse.wb.core.model.ObjectInfo.refreshCreate0(ObjectInfo.java:516)
	at org.eclipse.wb.core.model.ObjectInfo.lambda$4(ObjectInfo.java:478)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
	at org.eclipse.wb.core.model.ObjectInfo.lambda$3(ObjectInfo.java:478)
	at org.eclipse.wb.internal.swing.utils.SwingUtils$2.run(SwingUtils.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@67ad4e8e
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1453.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.wb.internal.core.model.creation.ThisCreationSupport.create0(ThisCreationSupport.java:325)
	at org.eclipse.wb.internal.core.model.creation.ThisCreationSupport.create(ThisCreationSupport.java:301)
	... 49 more
Full context stack trace:

java.lang.Error: getContentPane()
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:70)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateExpression(JavaInfoEvaluationHelper.java:622)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluate(JavaInfoEvaluationHelper.java:499)
	at org.eclipse.wb.core.model.JavaInfo$8.postVisit(JavaInfo.java:1146)
	at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils$ExecutionFlowHandler.invoke(ExecutionFlowUtils.java:1288)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils$VisitorStub$ByteBuddy$F6K4mfyV.postVisit(Unknown Source)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3303)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
	at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:223)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3348)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3300)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:354)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement0(ExecutionFlowUtils.java:338)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visitStatement(ExecutionFlowUtils.java:318)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:251)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:232)
	at org.eclipse.wb.core.eval.ExecutionFlowUtils.visit(ExecutionFlowUtils.java:195)
	at org.eclipse.wb.core.model.JavaInfo.refresh_create(JavaInfo.java:1203)
	at org.eclipse.wb.core.model.ObjectInfo.refreshCreate0(ObjectInfo.java:516)
	at org.eclipse.wb.core.model.ObjectInfo.lambda$4(ObjectInfo.java:478)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runDesignTime(ExecutionUtils.java:146)
	at org.eclipse.wb.core.model.ObjectInfo.lambda$3(ObjectInfo.java:478)
	at org.eclipse.wb.internal.swing.utils.SwingUtils$2.run(SwingUtils.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Error: <null>
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:70)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:114)
	at org.eclipse.wb.internal.core.eval.evaluators.InvocationEvaluator.evaluate(InvocationEvaluator.java:78)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:160)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
	... 41 more
Caused by: org.eclipse.wb.internal.core.utils.exception.DesignerException: 313 (Exception during 'super' constructor evaluation). JDialog(Frame) {javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]} java.lang.IllegalArgumentException: java.lang.ClassCastException@67ad4e8e
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1453.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.wb.internal.core.model.creation.ThisCreationSupport.create(ThisCreationSupport.java:308)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper.evaluateJavaInfoUsingCreationSupport(JavaInfoEvaluationHelper.java:634)
	at org.eclipse.wb.internal.core.model.JavaInfoEvaluationHelper$3.evaluate(JavaInfoEvaluationHelper.java:346)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate0(AstEvaluationEngine.java:123)
	at org.eclipse.wb.core.eval.AstEvaluationEngine.evaluate(AstEvaluationEngine.java:59)
	... 45 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@67ad4e8e
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor1453.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.wb.internal.core.model.creation.ThisCreationSupport.create0(ThisCreationSupport.java:325)
	at org.eclipse.wb.internal.core.model.creation.ThisCreationSupport.create(ThisCreationSupport.java:301)
	... 49 more

**Comment by ptziegler** [comment]
Hm... looks like the dummy object is causing problems. Perhaps my initial approach was too complicated and I have to accept that JDialogs can't be parsed properly. I.e. they should categorically be replaced by a dummy object. Otherwise you have endless combinations to somehow make them modal.

That said, you won't be happy with the preview, even if this code snippet wouldn't cause an error...

Because the empty JFrame is the owner of the dialog, is is treated as the entry point for the editor. Which has the beautiful side-effect that nothing you add to the dialog will be captured.

Meaning you get something like this:
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/423db3be-b919-4d40-b5fa-beae480a662e)

As opposed to this:
![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/9e46222f-ad27-46aa-ad37-e28a4dc84f0e)

But I think I have a solution for both problems.

**Comment by ptziegler** [comment]
Let's hope the second approach works... Instead of creating a stub, windows created inside the root widget are simply ignored.
