### ISSUE TITLE
Widget "Properties" not shown in java SWT Dialog Design view

### ISSUE THREAD

**Issue by ffedeli** [eclipse-windowbuilder/windowbuilder#760]
After updating WindowBuilder to **_1.16.0 Milestone_**, widget property list (**Properties** panel in java SWT Dialogs **Design** view) doesn't show any element, it's completely empty.

Eclipse Version: 2023-12 (4.30.0) Build id: 20231201-2043

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/34574583/0fe13270-f149-445f-bea1-1e27534d4b52)

**Comment by ptziegler** [comment]
Let me repeat my questions from the discussion...

> From a clean 4.31 with WindowBuilder M2:
>
> ![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/8779b331-3a9b-4c8b-a9df-9d50f8c171c7)
>
> What version of GEF is installied in your Eclipse? The property table depends on the class that has only been added in the latest milestone.
>
> Can you check if anything is logged in the error view?

**Comment by ffedeli** [comment]
**That is my Eclipse GEF version.** 

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/34574583/b0992a5f-a6b4-4563-bc03-5968babd54f5)

**And this is the error log**

!ENTRY org.eclipse.wb.core 4 4 2024-05-07 18:37:39.167
!MESSAGE Designer [1.16.0.202404302035.202405071834]: org/eclipse/draw2d/SeparatorBorder
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/draw2d/SeparatorBorder
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable$PropertyEditPart.createFigure(PropertyTable.java:1038)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:471)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.unregisterVisuals(AbstractGraphicalEditPart.java:895)
	at org.eclipse.gef.editparts.AbstractEditPart.unregister(AbstractEditPart.java:1142)
	at org.eclipse.gef.editparts.AbstractEditPart.removeNotify(AbstractEditPart.java:934)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.removeNotify(AbstractGraphicalEditPart.java:791)
	at org.eclipse.gef.editparts.AbstractEditPart.lambda$14(AbstractEditPart.java:933)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.gef.editparts.AbstractEditPart.removeNotify(AbstractEditPart.java:933)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.removeNotify(AbstractGraphicalEditPart.java:791)
	at org.eclipse.gef.editparts.AbstractEditPart.removeChild(AbstractEditPart.java:865)
	at org.eclipse.gef.editparts.SimpleRootEditPart.setContents(SimpleRootEditPart.java:111)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setContents(AbstractEditPartViewer.java:663)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setContents(AbstractEditPartViewer.java:672)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.setInput0(PropertyTable.java:462)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.setInput(PropertyTable.java:400)
	at org.eclipse.wb.internal.core.editor.structure.property.ComponentsPropertiesPage.showProperties(ComponentsPropertiesPage.java:552)
	at org.eclipse.wb.internal.core.editor.structure.property.ComponentsPropertiesPage.lambda$6(ComponentsPropertiesPage.java:517)
	at org.eclipse.wb.internal.core.utils.execution.ExecutionUtils.runLog(ExecutionUtils.java:107)
	at org.eclipse.wb.internal.core.editor.structure.property.ComponentsPropertiesPage.refreshProperties(ComponentsPropertiesPage.java:513)
	at org.eclipse.wb.internal.core.editor.structure.property.ComponentsPropertiesPage.setSelection(ComponentsPropertiesPage.java:314)
	at org.eclipse.wb.internal.core.editor.structure.DesignComponentsComposite.lambda$0(DesignComponentsComposite.java:70)
	at org.eclipse.wb.internal.core.utils.gef.EditPartsSelectionProvider.fireSelectionChanged(EditPartsSelectionProvider.java:115)
	at org.eclipse.wb.internal.core.utils.gef.EditPartsSelectionProvider$1.selectionChanged(EditPartsSelectionProvider.java:40)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.lambda$0(AbstractEditPartViewer.java:193)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:193)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.setSelection(AbstractEditPartViewer.java:255)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage.setSelection(ComponentsTreePage.java:215)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage.selectTreeViewer(ComponentsTreePage.java:144)
	at org.eclipse.wb.internal.core.editor.structure.components.ComponentsTreePage$2.selectionChanged(ComponentsTreePage.java:134)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.lambda$0(AbstractEditPartViewer.java:193)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:193)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.appendSelection(AbstractEditPartViewer.java:225)
	at org.eclipse.wb.internal.gef.core.AbstractEditPartViewer.select(AbstractEditPartViewer.java:270)
	at org.eclipse.wb.gef.core.tools.SelectEditPartTracker.performSelection(SelectEditPartTracker.java:145)
	at org.eclipse.wb.gef.core.tools.SelectEditPartTracker.handleButtonDown(SelectEditPartTracker.java:73)
	at org.eclipse.wb.gef.core.tools.Tool.mouseDown(Tool.java:258)
	at org.eclipse.wb.gef.graphical.tools.SelectionTool.mouseDown(SelectionTool.java:247)
	at org.eclipse.wb.internal.gef.core.EditDomain.mouseDown(EditDomain.java:241)
	at org.eclipse.wb.internal.gef.graphical.EditEventManager.lambda$1(EditEventManager.java:135)
	at org.eclipse.wb.internal.draw2d.EventManager.delayEvent(EventManager.java:352)
	at org.eclipse.wb.internal.gef.graphical.EditEventManager.dispatchMousePressed(EditEventManager.java:123)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseDown(LightweightSystem.java:568)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4273)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4071)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
Caused by: java.lang.ClassNotFoundException: org.eclipse.draw2d.SeparatorBorder cannot be found by org.eclipse.wb.core_1.16.0.202404302035
	... 72 more

**Comment by ptziegler** [comment]
Thanks! That's exactly what I feared... the version of GEF hasn't been updated.

To fix this, you need to manually update GEF using the following update site:
https://download.eclipse.org/tools/gef/classic/milestone/S202405011806

Go to Help -> Install New Software and select both Draw2D and GEF in the dialog.

![image](https://github.com/eclipse-windowbuilder/windowbuilder/assets/70652978/ba280bc1-ea73-48d8-9baf-f3393c8a1bd0)

**Comment by ffedeli** [comment]
My GEF version is indeed quite old, I'll upgrade it as soon as possible
thank you very much

**Comment by ffedeli** [comment]
Done!!!
That's all right now, I'm closing this issue
Thanks a lot

**Comment by ptziegler** [comment]
Happy to hear. 😄 I'll try to adapt the project dependencies in the next few days so that hopefully WindowBuilder automatically installs any dependencies in their correct version.
