### ISSUE TITLE
ClassCastException when using custom layout manager

### ISSUE THREAD

**Issue by ptziegler** [eclipse-windowbuilder/windowbuilder#793]
To reproduce:

- Set the default layout manager to e.g. "BorderLayout" in the Swing preferences
- Create a new JFrame
- Add a JButton to the content pane.

The problem:

The layout manager isn't set for the JButton and is therefore using the FlowLayout by default. But WindowBuilder assumes it to be a BorderLayout, as this is what's set in tne preferences.

Stacktrace:

```
java.lang.ClassCastException: class java.awt.FlowLayout cannot be cast to class java.awt.BorderLayout (java.awt.FlowLayout and java.awt.BorderLayout are in module java.desktop of loader 'bootstrap')
	at org.eclipse.wb.internal.swing.model.layout.BorderLayoutInfo$ConstraintsProperty.getValue(BorderLayoutInfo.java:226)
	at org.eclipse.wb.internal.core.model.property.editor.StringComboPropertyEditor.getText(StringComboPropertyEditor.java:41)
	at org.eclipse.wb.internal.core.model.property.editor.TextDisplayPropertyEditor.paint(TextDisplayPropertyEditor.java:35)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable$PropertyFigure.paintClientArea(PropertyTable.java:1150)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1312)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.ScalableLayeredPane.paintClientArea(ScalableLayeredPane.java:90)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Viewport.paintClientArea(Viewport.java:161)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.DeferredUpdateManager.paint(DeferredUpdateManager.java:168)
	at org.eclipse.draw2d.LightweightSystem.paint(LightweightSystem.java:202)
	at org.eclipse.draw2d.LightweightSystem.lambda$0(LightweightSystem.java:110)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1184)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1169)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1540)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4769)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.RedrawWindow(Native Method)
	at org.eclipse.swt.widgets.Control.update(Control.java:4549)
	at org.eclipse.swt.widgets.Control.update(Control.java:4542)
	at org.eclipse.wb.internal.core.utils.exception.DesignerExceptionUtils.makeScreenshot(DesignerExceptionUtils.java:533)
	at org.eclipse.wb.internal.core.editor.DesignPage.handleDesignException(DesignPage.java:655)
	at org.eclipse.wb.internal.core.editor.DesignPage$9.handleException(DesignPage.java:581)
	at org.eclipse.wb.internal.core.editor.structure.property.ComponentsPropertiesPage.lambda$0(ComponentsPropertiesPage.java:101)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.handleException(PropertyTable.java:283)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.activateEditor(PropertyTable.java:213)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable$PropertyEditDomain.mouseDown(PropertyTable.java:682)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMousePressed(DomainEventDispatcher.java:396)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseDown(LightweightSystem.java:568)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:209)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4083)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:679)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:616)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1492)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1465)
```

**Comment by ptziegler** [comment]
No longer reproducible on master. My guess is that the paint method was called while the editor was in an inconsistent state. This should no longer be possible with 7accf5c34ada49446a8392c289683630e4797e15.
