### ISSUE TITLE
Segmentation Fault during tests when running on Linux

### ISSUE THREAD

**Issue by ptziegler** [eclipse-windowbuilder/windowbuilder#946]
See https://github.com/eclipse-windowbuilder/windowbuilder/pull/945
[hs_err_pid83762.log](https://github.com/user-attachments/files/18158311/hs_err_pid83762.log)

This issue doesn't happen when I switch back to the 2024-12 update site, so it _must_ be a regression introduced by the Eclipse Platform. ☹️

**Comment by ptziegler** [comment]
Doesn't seem to be the first time this happens...

https://bugs.eclipse.org/bugs/show_bug.cgi?id=541203
https://bugs.eclipse.org/bugs/show_bug.cgi?id=547223
https://bugs.eclipse.org/bugs/show_bug.cgi?id=563390

**Comment by ptziegler** [comment]
I believe that this is an issue in the SWT_AWT component. This is the AwtComponentDialog in which the segmentation fault occurs. Obviously, the Swing frame is missing.

![image](https://github.com/user-attachments/assets/1b4eb7e6-2946-4168-ae7c-03aaee28ae73)

My current assumption: A ficticious SWT_AWT handle is created and added to the shell. When the shell is disposed, SWT attempts to also destroy this non-existing handle, which then leads to a crash.

**Comment by ptziegler** [comment]
Hm... I also see this error in https://github.com/eclipse-windowbuilder/windowbuilder/actions/runs/12016996794/job/33498384774, i.e. while still using the 2024-12 update site:

```
2024-11-25T19:19:26.2848172Z org.eclipse.swt.SWTException: Return value not valid. g_object_get_qdata returned unexpected index value, index: -1, table size: 1024
2024-11-25T19:19:26.2849102Z 	at org.eclipse.swt.SWT.error(SWT.java:4922)
2024-11-25T19:19:26.2849673Z 	at org.eclipse.swt.widgets.Display.removeWidget(Display.java:4984)
2024-11-25T19:19:26.2850406Z 	at org.eclipse.swt.widgets.Composite.deregister(Composite.java:521)
2024-11-25T19:19:26.2851133Z 	at org.eclipse.swt.widgets.Widget.releaseWidget(Widget.java:1435)
2024-11-25T19:19:26.2851874Z 	at org.eclipse.swt.widgets.Control.releaseWidget(Control.java:4775)
2024-11-25T19:19:26.2852644Z 	at org.eclipse.swt.widgets.Composite.releaseWidget(Composite.java:1577)
2024-11-25T19:19:26.2853373Z 	at org.eclipse.swt.widgets.Widget.release(Widget.java:1413)
2024-11-25T19:19:26.2854021Z 	at org.eclipse.swt.widgets.Control.release(Control.java:4753)
2024-11-25T19:19:26.2854755Z 	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1560)
2024-11-25T19:19:26.2855484Z 	at org.eclipse.swt.widgets.Widget.release(Widget.java:1401)
2024-11-25T19:19:26.2856351Z 	at org.eclipse.swt.widgets.Control.release(Control.java:4753)
2024-11-25T19:19:26.2857077Z 	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1560)
2024-11-25T19:19:26.2857956Z 	at org.eclipse.swt.widgets.Widget.release(Widget.java:1401)
2024-11-25T19:19:26.2858376Z 	at org.eclipse.swt.widgets.Control.release(Control.java:4753)
2024-11-25T19:19:26.2858791Z 	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1560)
2024-11-25T19:19:26.2859233Z 	at org.eclipse.swt.widgets.Canvas.releaseChildren(Canvas.java:279)
2024-11-25T19:19:26.2859789Z 	at org.eclipse.swt.widgets.Decorations.releaseChildren(Decorations.java:503)
2024-11-25T19:19:26.2860242Z 	at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:3435)
2024-11-25T19:19:26.2860629Z 	at org.eclipse.swt.widgets.Widget.release(Widget.java:1401)
2024-11-25T19:19:26.2860991Z 	at org.eclipse.swt.widgets.Control.release(Control.java:4753)
2024-11-25T19:19:26.2861349Z 	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:575)
2024-11-25T19:19:26.2861827Z 	at org.eclipse.swt.widgets.Shell.dispose(Shell.java:3352)
2024-11-25T19:19:26.2862216Z 	at org.eclipse.jface.window.Window.close(Window.java:335)
2024-11-25T19:19:26.2862607Z 	at org.eclipse.jface.dialogs.Dialog.close(Dialog.java:987)
2024-11-25T19:19:26.2863114Z 	at org.eclipse.wb.internal.core.utils.ui.dialogs.ResizableDialog.close(ResizableDialog.java:207)
2024-11-25T19:19:26.2863762Z 	at org.eclipse.wb.internal.swing.customize.AwtComponentDialog.close(AwtComponentDialog.java:119)
```

So this seems to be broken in general. But instead of simply not working, the test now also causes a crash.

**Comment by ptziegler** [comment]
It's a timing issue. This method returns before the Swing Frame has been properly disposed, leaving the dialog in a broken state.

https://github.com/eclipse-windowbuilder/windowbuilder/blob/8ba6671c7435aaf76968e0105262d64c9d01e87a/org.eclipse.wb.swing/src/org/eclipse/wb/internal/swing/customize/AwtComponentDialog.java#L130-L150
